### PR TITLE
自学训练营学习10群day1

### PR DESCRIPTION
**Pull request by leisureDL**
I don't know what I had done
@realcaiying

### CODE REVIEW

**Comment by seven-tears** [comment]
备注下那个群，第几天作业

**Comment by leisureDL** [comment]
> I don't know what I had done
> @realcaiying

自学训练营学习10群，day1

**Comment by leisureDL** [comment]
我好像完成作业了？

**Comment by realcaiying** [comment]
第一天的作业文件有了。不过需要补充一个 README.md 文件哈

**Pull request merged**
